In [ ]:
!pip install pyspark

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyspark
  Downloading pyspark-3.3.0.tar.gz (281.3 MB)
     |████████████████████████████████| 281.3 MB 40 kB/s
Collecting py4j==0.10.9.5
  Downloading py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)
     |████████████████████████████████| 199 kB 48.4 MB/s
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.3.0-py2.py3-none-any.whl size=281764026 sha256=7705f0f793c80c7915fc66f472e0f848dde1bdaa175e26dfafd4e1ff0b3944f8
  Stored in directory: /root/.cache/pip/wheels/7a/8e/1b/f73a52650d2e5f337708d9f6a1750d451a7349a867f928b885
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.5 pyspark-3.3.0

In [ ]:
from pyspark.sql import SparkSession
spark= SparkSession.builder.appName("Spark Transform").getOrCreate()

##**Spark Transformation**

# There are 2 types of approaches to trasforming the data by dataframe(progamatic approach) n table(sql interface) both are same. 
# Spark program interacts with dataframe n spark sql with table

1. Combining dataframe
2. Aggregation n Summarizing
3. Applying fun n built in transformation
4. Using built-in n column level fn
5. UDF's
6. refer col n rows
7. creating column expression

In [ ]:
# Working with datafrmae rows Dataframe = dataset[Rows]
# Senarios 1. Manually creating rows and columns 2. Collecting dataframe rows to driver 3. Work with a individual row in Spark Transformation

##**Dataframe Columns**

1. How to reference a column 
2. How ot create column expression

There are 2 ways to refer to the columns. 

1. Column String
2. Column Object

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving walmart_stock.csv to walmart_stock.csv
User uploaded file "walmart_stock.csv" with length 90266 bytes

In [ ]:
df = spark.read.option('header','true').format('CSV').option('inferSchema','true').load('walmart_stock.csv')

In [ ]:
df.printSchema()

root
 |-- Date: timestamp (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Volume: integer (nullable = true)
 |-- Adj Close: double (nullable = true)

In [8]:
#Column String
df.select('Date','Open').show(10)

+-------------------+------------------+
|               Date|              Open|
+-------------------+------------------+
|2012-01-03 00:00:00|         59.970001|
|2012-01-04 00:00:00|60.209998999999996|
|2012-01-05 00:00:00|         59.349998|
|2012-01-06 00:00:00|         59.419998|
|2012-01-09 00:00:00|         59.029999|
|2012-01-10 00:00:00|             59.43|
|2012-01-11 00:00:00|         59.060001|
|2012-01-12 00:00:00|59.790001000000004|
|2012-01-13 00:00:00|             59.18|
|2012-01-17 00:00:00|         59.869999|
+-------------------+------------------+
only showing top 10 rows

In [10]:
# Column Object

from pyspark.sql.functions import *
df.select(column("Volume"),col("Date"),df.Close).show(10)

+--------+-------------------+------------------+
|  Volume|               Date|             Close|
+--------+-------------------+------------------+
|12668800|2012-01-03 00:00:00|         60.330002|
| 9593300|2012-01-04 00:00:00|59.709998999999996|
|12768200|2012-01-05 00:00:00|         59.419998|
| 8069400|2012-01-06 00:00:00|              59.0|
| 6679300|2012-01-09 00:00:00|             59.18|
| 6907300|2012-01-10 00:00:00|59.040001000000004|
| 6365600|2012-01-11 00:00:00|         59.400002|
| 7236400|2012-01-12 00:00:00|              59.5|
| 7729300|2012-01-13 00:00:00|59.540001000000004|
| 8500000|2012-01-17 00:00:00|         59.849998|
+--------+-------------------+------------------+
only showing top 10 rows

In [ ]:
# Create column expression
#There are 2 types of expression. 1. String expression/SQL expression 2. Column object expression
#1. SQL Expression

In [ ]:
# UDF User defined function